### ISSUE TITLE
Flaky CI.

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1045]
This seems to deserve a proper fix. 

https://buildkite.com/nearprotocol/near-sdk-rs/builds/4790#01890e24-4dcb-410f-8a06-b1311b695692

```


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', chain/jsonrpc/src/lib.rs:1582:33
--
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  | 1: core::panicking::panic_fmt
  | at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  | 2: core::result::unwrap_failed
  | at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  | 3: nearcore::start_with_config_and_synchronization
  | 4: neard::cli::RunCmd::run::{{closure}}
  | 5: tokio::task::local::LocalSet::run_until::{{closure}}
  | 6: neard::cli::NeardCmd::parse_and_run
  | 7: neard::main
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | Error: Failed to connect to RPC service http://localhost:16010 within 10 seconds
  |  
  | Caused by:
  | error while sending payload: [error sending request for url (http://localhost:16010/): connection closed before message completed]
  | test simulate_transfer_call_promise_panics_for_a_full_refund ... FAILED


```

**Comment by frol** [comment]
I think it should be fixed with https://github.com/near/workspaces-rs/pull/277 (not released yet)

**Comment by ruseinov** [comment]
Let's close this then!
