### ISSUE TITLE
Runtime error in rust-counter example after upgrading to near-sdk 0.11.0

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-sdk-rs#186]
This is the PR that fails https://github.com/near-examples/rust-counter/pull/21
Error details: 
```
FAIL  src/test.js (7.721s)
  Token
    counter
      ✕ can be incremented (64ms)
      ✕ can be decremented (2271ms)
      ✕ can be reset (1707ms)
  ● Token › counter › can be incremented
    Querying call/test1591745275168/get_num failed: wasm execution failed with error: FunctionCallError(LinkError { msg: "2 link errors: (1 of 2) Import not found, namespace: env, name: validator_stake (2 of 2) Import not found, namespace: env, name: validator_total_stake" }).
    {
      "error": "wasm execution failed with error: FunctionCallError(LinkError { msg: \"2 link errors: (1 of 2) Import not found, namespace: env, name: validator_stake (2 of 2) Import not found, namespace: env, name: validator_total_stake\" })",
      "logs": [],
      "block_height": 2370609,
      "block_hash": "ChCezDc7rDWaCjAxh2ZE1mYQyXoFy699xYzoL9HxjNbN"
    }
      19 |   describe('counter', function () {
      20 |     it('can be incremented', async function () {
    > 21 |       const startCounter = await contract.get_num();
         |                            ^
      22 |       await contract.increment();
      23 |       const endCounter = await contract.get_num();
      24 |       expect(endCounter).toEqual(startCounter + 1);
      at JsonRpcProvider.query (node_modules/near-api-js/lib/providers/json-rpc-provider.js:63:19)
      at Account.viewFunction (node_modules/near-api-js/lib/account.js:243:24)
      at Object.<anonymous> (src/test.js:21:28)
```

**Comment by nearmax** [comment]
Seems like you are not using the most recent node.
