### ISSUE TITLE
Using panic! doesn't show error message

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#214]
If `panic!(message)` used in the contract, the resulting error doesn't contain the message:
```
"status":{"Failure":{"ActionError":{"index":0,"kind":{"FunctionCallError":{"HostError":{"GuestPanic":{"panic_msg":"panicked at src/lib.rs:202:23"}}}}
```

Expectation: "panic_msg" has the message. 
The traceback is in the different field.

**Comment by evgenykuzyakov** [comment]
It seems like it does show the message: `panicked at src/lib.rs:202:23`
Do you have a contract where it doesn't?

**Comment by bowenwang1996** [comment]
@evgenykuzyakov it doesn't show the message you logged. If you do `panic!("PANIC")` it doesn't show `PANIC`

**Comment by evgenykuzyakov** [comment]
I verified it does record the message. The reason you haven't seen the message is the `panic!()` was called without an argument.

See PR: https://github.com/near/near-sdk-rs/pull/230

Tested using `near-vm-runner-standalone`

```
near-vm-runner-standalone --wasm-file res/test_contract.wasm  --method-name=test_panic_macro
{"outcome":{"balance":"10000000000000000000000000","storage_usage":100,"return_data":"None","burnt_gas":115595266842,"used_gas":115595266842,"logs":[]},"err":{"FunctionCallError":{"HostError":{"GuestPanic":{"panic_msg":"panicked at 'PANIC!', src/lib.rs:31:9"}}}},"receipts":[],"state":{}}
```

**Comment by bowenwang1996** [comment]
Should we close this then @ilblackdragon ?

**Comment by austinabell** [comment]
Will close this in favour of using #190 for discussion on this
