### ISSUE TITLE
TreeMap panic on inser after remove last value [unstable]

### ISSUE THREAD

**Issue by dkotTech** [near/near-sdk-rs#993]
lib.rs
```rust
use near_sdk::borsh::{self, BorshDeserialize, BorshSerialize};
use near_sdk::store::tree_map::Entry;
use near_sdk::store::TreeMap;
use near_sdk::{log, near_bindgen, AccountId, BorshStorageKey, PanicOnDefault};

#[near_bindgen]
#[derive(BorshDeserialize, BorshSerialize, PanicOnDefault)]
pub struct Contract {
    tree_map: TreeMap<AccountId, bool>,
}

#[derive(BorshSerialize, BorshStorageKey)]
enum StorageKey {
    Storage,
}

#[near_bindgen]
impl Contract {
    #[init]
    pub fn new() -> Self {
        Self {
            tree_map: TreeMap::new(StorageKey::Storage),
        }
    }

    pub fn switch(&mut self, account_id: AccountId) {
        match self.tree_map.entry(account_id) {
            Entry::Occupied(o) => {
                o.remove();
                log!("removed");
            }
            Entry::Vacant(o) => {
                o.insert(true);
                log!("inserted");
            }
        };
    }
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::*;

    #[test]
    fn test_ok() {
        let mut contract = Contract::new();

        contract.switch("account_near".parse().unwrap()); // inserted
        contract.switch("account1_near".parse().unwrap()); // inserted
        contract.switch("account_near".parse().unwrap()); // removed
        contract.switch("account_near".parse().unwrap()); // inserted

        contract.switch("account_near".parse().unwrap()); // removed
    }

    #[test]
    fn test_panic() {
        let mut contract = Contract::new();

        contract.switch("account_near".parse().unwrap()); // inserted
        contract.switch("account_near".parse().unwrap()); // remove
        contract.switch("account_near".parse().unwrap()); // panic

        contract.switch("account_near".parse().unwrap());
    }
}

// inserted
// removed
// thread 'tests::test_panic' panicked at 'called `Result::unwrap()` on an `Err` value: HostError(GuestPanic { panic_msg: "explicit guest panic" })', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mocked_blockchain.rs:192:78
// stack backtrace:
//    0: rust_begin_unwind
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
//    1: core::panicking::panic_fmt
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
//    2: core::result::unwrap_failed
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
//    3: core::result::Result<T,E>::unwrap
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
//    4: near_sdk::environment::mock::mocked_blockchain::mock_chain::with_mock_interface::{{closure}}
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mocked_blockchain.rs:192:49
//    5: near_sdk::environment::mock::with_mocked_blockchain::{{closure}}
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mod.rs:25:35
//    6: std::thread::local::LocalKey<T>::try_with
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
//    7: std::thread::local::LocalKey<T>::with
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
//    8: near_sdk::environment::mock::with_mocked_blockchain
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mod.rs:25:5
//    9: near_sdk::environment::mock::mocked_blockchain::mock_chain::with_mock_interface
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mocked_blockchain.rs:192:9
//   10: panic
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/mock/mocked_blockchain.rs:299:9
//   11: near_sdk::environment::env::abort
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/environment/env.rs:688:9
//   12: near_sdk::store::tree_map::expect::{{closure}}
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/store/tree_map/mod.rs:20:27
//   13: core::option::Option<T>::unwrap_or_else
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:825:21
//   14: near_sdk::store::tree_map::expect
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/store/tree_map/mod.rs:20:5
//   15: near_sdk::store::tree_map::Tree<K>::internal_insert
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/store/tree_map/mod.rs:538:24
//   16: near_sdk::store::tree_map::entry::VacantEntry<K,V>::insert
//              at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-4.1.1/src/store/tree_map/entry.rs:404:9
//   17: tree_map_issue::Contract::switch
//              at ./src/lib.rs:33:17
//   18: tree_map_issue::tests::test_panic
//              at ./src/lib.rs:62:9
//   19: tree_map_issue::tests::test_panic::{{closure}}
//              at ./src/lib.rs:57:5
//   20: core::ops::function::FnOnce::call_once
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
//   21: core::ops::function::FnOnce::call_once
//              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
// note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
// test tests::test_panic ... FAILED
//
// failures:
//
// failures:
//     tests::test_panic
//
// test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

```

Cargo.toml
```toml
[package]
name = "tree-map-issue"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = {version="4.1.1",features = ["unstable"]}

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
```

**Comment by austinabell** [comment]
Confirmed; thanks for the report! Looking into the fix now
